image: Ubuntu2204 # образ для сборки

environment:
  matrix:
    - nodejs_version: "20"

branches:
  only:
    - master # ветка git
    - main

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей
  # - npx puppeteer browsers install chrome

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build # команда сборки

test_script:
  #- npm run e2e

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
